### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by ghaerdi** [crewdevio/Trex#140]
### Should have
- [ ] Remove script runner. Maybe keep installation lifecycle.
- [ ] Remove integrity checking,
- [ ] Install from standard library first when using `--mod` flag, if can't find the name in the standard library then check in third-party libraries.
- [ ] Add a way to install a third-party library with the same name as the standard.
- [ ] Make `--mod` as default by using `install` subcommand.
- [ ] Use `deno.json(c)` file as default importMap.

### Maybe
- [ ] Subcommand to parse npm scripts to deno tasks.
- [ ] Subcoomand to parse npm depedencies to deno importMap

### Probably before v2
- [ ] Support to `npm:` packages.
- [ ] Support to `node:` packages.
- [ ] Support to `deno.json(c)` importMap
